using Test
include("helpers.jl")

@testset "Kanon — F1 a F6" begin
    include("test_source.jl")
    include("test_pragma.jl")
    include("test_structure.jl")
    include("test_data.jl")
    include("test_text.jl")
    include("test_rules.jl")
    include("test_diagnostics.jl")
    include("test_invariants.jl")
    include("test_types.jl")
    include("test_environment.jl")
    include("test_analyze.jl")
    include("test_guarded.jl")
    include("test_references.jl")
    include("test_rule_semantics.jl")
    include("test_acceptance.jl")
    include("test_check.jl")
    include("test_contract.jl")
    include("test_render.jl")
    include("test_security.jl")
    include("test_cli.jl")
    include("test_rules_runtime.jl")
    include("test_neutralidade.jl")
end
